{
  getObjects(
    bucket_slug: "kemiljk"
    input: {
      read_key: "uNXYQDbNTCWQyEaFjq44PUolieGKBuzePTaEdnDl0CHLcnJtPK"
      query: { type: "blogs" }
    }
  ) {
    objects {
      id
      slug
      title
      content
      metadata
      modified_at
      order
    }
    total
  }
}
